//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TricornFieldEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"PUS|RD|PDU|HVTRU|F88R|GW|VPU|GWR|HTR|PCB|EXH|LV|LH|RH|LVPSU|AER|BAE|BBC|BDR|CEF|CPS|CSI|GKM|IPE|LMR|MCT|SJC|SME|TBS|TMD|AJ|HF|GB|UK|E2V|CCD|CIS|CR|HV|FET|TX|JAS|KMT|FPA|LNA|ALS|RM12|RPD|RX|SLAA|SMA|DLR|GPS|BA|STX|TX3R|TJLJ2|TNC|MTG|TVG|TWT|VR|VHRI|LHS|HSG|WRD")]
        public string SavedAcronyms {
            get {
                return ((string)(this["SavedAcronyms"]));
            }
            set {
                this["SavedAcronyms"] = value;
            }
        }
    }
}
